import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ApolloWrapper } from './ApolloWrapper';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { GlobalProvider } from './context';
import PageHeader from './components/PageHeader';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Notes',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <GlobalProvider>
          <body className={inter.className}>
            <PageHeader />
            <ApolloWrapper>{children}</ApolloWrapper>
          </body>
        </GlobalProvider>
      </UserProvider>
    </html>
  );
}
